version: '3.8'

services:
  app:
    build: 
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=cloud-storage
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cloud-storage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
