version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cloud-storage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    networks:
      - backend

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    networks:
      - backend
    environment:
      - SECRET_KEY=django-insecure-=(kh-486vwl^ixi8+duxs$7c!_qsq@+r$ssmn@wioav=a^fq)*
      - DB_NAME=cloud-storage
      - DB_USER=postgres
      - DB_PASSWORD=root
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  minio:
    image: minio/minio:latest
    command: server /data
    ports:
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
