# Generated by Django 5.0.6 on 2024-06-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='user_id',
            new_name='user',
        ),
    ]
