# Generated by Django 5.0.6 on 2024-06-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='token',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
