# Generated by Django 5.0.6 on 2024-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usersession_token_usersession_user_agent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='user_sessions',
        ),
    ]
