# Generated by Django 5.0.6 on 2024-06-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_table_alter_usersession_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='user_session',
        ),
    ]
