# Generated by Django 5.0.6 on 2024-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_table_alter_usersession_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(max_length=36),
        ),
    ]
